# Generated by Django 4.0.4 on 2022-07-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team_user_firstlogindate_user_firstmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channelid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
