# Generated by Django 4.0.4 on 2022-07-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_channel_channelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='channel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.channel'),
            preserve_default=False,
        ),
    ]
