# Generated by Django 4.0.4 on 2022-07-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_messages_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='channel',
            new_name='channelid',
        ),
    ]
