# Generated by Django 4.0.4 on 2022-07-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_channel_messages_channelid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user',
            new_name='userid',
        ),
    ]
