# Generated by Django 4.0.4 on 2022-07-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_channel_id_alter_team_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teamid',
            field=models.ManyToManyField(to='main.team'),
        ),
    ]
