# Generated by Django 4.0.4 on 2022-07-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_teamid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='channelid',
        ),
    ]
