# Generated by Django 4.0.4 on 2022-08-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_messages_messageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='contenttype',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
