# Generated by Django 4.0.4 on 2022-08-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_messages_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='teamid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
            preserve_default=False,
        ),
    ]
