# Generated by Django 4.0.4 on 2022-08-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_messages_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstlogindate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
