# Generated by Django 4.0.4 on 2022-08-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_user_firstmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackGivenPdf', models.BooleanField()),
                ('teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
