# Generated by Django 4.0.4 on 2022-08-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_feedbackupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.CharField(max_length=300)),
                ('teamid', models.CharField(max_length=200, unique=True)),
                ('uploaddate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
