# Generated by Django 4.0.4 on 2022-08-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
