# Generated by Django 4.0.4 on 2022-08-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_upload_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggerdate', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=800)),
                ('teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
